### PR TITLE
fix: gen lender lowest APR and general improvements

### LINKED ISSUE #205: Gen Lender: Invalid Lowest APR
https://yearn.watch/network/ethereum/vault/0x6d765CbE5bC922694afE112C140b8878b9FB0390/strategy/0x79Be3edA1d7FE92c18B9539bce2611bf8dc9BFc5

image

### PR DESCRIPTION
**Pull request by edwinzhng**
Fixes #205

- Does not display unreasonably high APR if it is returned by the strategy anymore
- Lender names are now displayed along with the index to make it easier to read
- Cleaned up code

Screen Shot 2022-02-06 at 4 18 01 PM

### CODE REVIEW

File: src/components/app/SingleStrategy/GenLender.tsx [hunk 1]
```diff
@@ -27,99 +26,106 @@ type GenLenderProps = {
...
-                            <div>
-                                APR: {displayAprAmount(value[2].toString())}
-                            </div>
-                        </Box>
-                    ))}
-                </>
-            ) : (
-                ''
-            );
+        const lenderStatuses = data ? (
```
Comment (karelianpie) [inline src/components/app/SingleStrategy/GenLender.tsx]: It appears we have a bunch of ternary operators here checking if we have `data`, could we just return `null` if there's no `data` vs having all this logic and assigning empty strings to constants?

File: src/components/app/SingleStrategy/GenLender.tsx [hunk 2]
```diff
@@ -130,16 +136,16 @@ export const GenLender = (props: GenLenderProps) => {
...
             },
         ];
-        return <CardContent data={data} key={strategy.address} />;
+        return <CardContent data={cardData} key={strategy.address} />;
     };
 
     return (
         <>
-            {isLoading ? (
+            {loading ? (
```
Comment (karelianpie) [inline src/components/app/SingleStrategy/GenLender.tsx]: I think we should not nest ternary operators, it makes reading a little bit hard.

Could we return based on the state instead

```typescript
if (loading) {
    return <StyledTypography>Loading...</StyledTypography>
}

if (error) {
    return <ErrorAlert message={error} />
}

// ...
```

We should also check for `loading && !data` rather than just `loading`, as we might not want to show loading when we are fetching results on the background. So we would only want to show the loading until we've got some data. This might be useful if in we have a `refetch`

File: src/components/app/SingleStrategy/GenLender.tsx [hunk 3]
```diff
@@ -27,99 +26,106 @@ type GenLenderProps = {
...
-                setIsLoading(false);
-            } catch (e: unknown) {
-                console.log('Error:', e);
-                setIsLoading(false);
-                setError(getError(e));
-            }
-        };
-        loadGenLenderData();
-    }, [strategy.address, network]);
+    const { data, loading, error } = useStrategyGenLender(
```
Comment (karelianpie) [inline src/components/app/SingleStrategy/GenLender.tsx:29]: 👍

File: src/components/app/SingleStrategy/GenLender.tsx (hunk 2 above)
Comment (edwinzhng) [reply src/components/app/SingleStrategy/GenLender.tsx]: Yeah I opened #208 to address this, but I can change it now

File: src/components/app/SingleStrategy/GenLender.tsx (hunk 1 above)
Comment (edwinzhng) [reply src/components/app/SingleStrategy/GenLender.tsx]: Yeah good idea, I will fix this. We have this pattern in a bunch of other locations as well, so I'll clean the other ones up after

**Comment by edwinzhng** [comment]
Thanks for reviewing, I addressed your comments @karelianpie but will probably need to create a follow up PR with the same fixes across a bunch of the other components so I opened up #209 to track this

File: src/components/app/SingleStrategy/GenLender.tsx [hunk 4]
```diff
@@ -57,7 +57,11 @@ export const GenLender = (props: GenLenderProps) => {
     };
 
     const renderData = () => {
-        const lenderStatuses = data ? (
+        if (!data) {
+            return <></>;
```
Comment (karelianpie) [inline src/components/app/SingleStrategy/GenLender.tsx]: Much better! Thanks @edwinzhng

nit: Usually the React team recommends returning `null` explicitly rather than Fragment, it has some optimisation benefits.

File: src/components/app/SingleStrategy/GenLender.tsx [hunk 5]
```diff
@@ -143,17 +136,13 @@ export const GenLender = (props: GenLenderProps) => {
...
-            )}
-        </>
-    );
+    if (loading) {
+        return <StyledTypography>Loading...</StyledTypography>;
+    }
+    if (error) {
+        return <ErrorAlert message={error} />;
+    }
+    return renderData();
```
Comment (karelianpie) [inline src/components/app/SingleStrategy/GenLender.tsx:145]: 👍

**Review by karelianpie — APPROVED** [review]
LGTM!

I'm still new to the codebase, you might want/need to wait for another reviewer in order to merge this in.

File: src/components/app/SingleStrategy/GenLender.tsx (hunk 4 above)
Comment (edwinzhng) [reply src/components/app/SingleStrategy/GenLender.tsx]: Ah good to know, I'll fix when I tackle the general cleanup

File: src/components/app/SingleStrategy/GenLender.tsx (hunk 5 above)
Comment (magikadev) [reply src/components/app/SingleStrategy/GenLender.tsx:145]: Good. 👌

**Review by magikadev — APPROVED** [review]
