### PR TITLE
fix: return 0 for longevity if activation is zero

### LINKED ISSUE #150: Longevity: Set 5 by default
When a group is created and it doesn't contain strategies, it displays 1 as a longevity score.

Example:

image

### PR DESCRIPTION
**Pull request by kyhoon**
Suggestion for #150

I assumed that the default activation for ProtocolTVL will stay as zero

### CODE REVIEW

File: src/types/protocol-tvl.ts [hunk 1]
```diff
@@ -10,6 +10,9 @@ export class ProtocolTVL {
     ) {}
 
     getLongevityDays(): number {
+        if (this.activation === 0) {
```
Comment (magikadev) [inline src/types/protocol-tvl.ts]: https://github.com/yearn/yearn-watch/blob/5d779c5c2645a9c15b3dd8fab4131708d42b6f57/src/utils/strategyParams.ts#L138

It would be better to use this validation check.

Comment (kyhoon) [reply src/types/protocol-tvl.ts]: added in e3a2e397160b55a3ae528b2d0e585b011025cddf

**Review by magikadev — APPROVED** [review]
